const N=(e,...p)=>({e,p});
window.NOTES={
// ---------- JAVASCRIPT ----------
"Hoisting":N("Before JavaScript runs your code, it first scans it and registers every variable and function name. So some things can be used before the line where you wrote them. Think of it as JS reading the whole menu before taking your order.",
"var is hoisted and starts as undefined, so using it early gives undefined, not an error.",
"Function declarations are hoisted completely, so you can call them before they are written.",
"let and const are hoisted too, but locked in the temporal dead zone until their line runs. Using them early throws ReferenceError.",
"Function expressions and arrow functions follow the variable rule (var/let/const), not the function rule."),
"Execution Context":N("An execution context is the environment JavaScript creates to run a piece of code. It holds the variables, functions and the value of this for that code. Whenever code runs, JS needs one, like a workspace for the task.",
"The Global Execution Context is created first, when the program starts.",
"Memory phase: variables and functions are stored. Execution phase: code runs line by line.",
"Each function call creates a new context, pushed on the Call Stack and popped when the function returns.",
"Call Stack is last in, first out: the function on top runs first."),
"Closures":N("A closure is a function that remembers the variables from the place where it was born, even after that outer function has finished. The inner function keeps a backpack with the outer variables inside.",
"Closure = function + its lexical scope (the variables around it when it was written).",
"Every call of the outer function creates a new, separate closure, so son1 and son2 have different money.",
"Outer variables stay alive in memory as long as the inner function can still use them.",
"Use cases: private data, counters, once-only functions, setTimeout inside loops, memoization."),
"var vs let vs const":N("These are the three ways to create a variable. They differ in scope (where the variable is visible), hoisting and whether you can reassign them.",
"var: function scope, can be redeclared, hoisted as undefined.",
"let: block scope (inside { }), can be reassigned, not redeclared in the same scope.",
"const: block scope, cannot be reassigned. Objects and arrays declared with const can still be changed inside.",
"Shadowing: a variable in an inner block with the same name hides the outer one only inside that block."),
"Types of Functions":N("A function is a reusable block of instructions. JavaScript lets you write functions in many styles, and each one has a small difference you should know for interviews.",
"Declaration: hoisted, has a name. Expression: stored in a variable, not hoisted.",
"Arrow function: shorter syntax, no own this, cannot be used with new.",
"IIFE runs immediately and keeps variables private. Generator uses function* and yield to pause and resume.",
"Async function always returns a Promise and lets you use await. Constructor function is used with new to build objects."),
"First-class & Higher-Order Functions":N("In JavaScript a function is just a value, like a number or a string. You can store it, pass it around and return it. That ability is called first-class functions.",
"First-class: assign to a variable, pass as argument, return from a function.",
"Higher-order function: a function that takes another function as input, or returns one.",
"Built-in examples: map, filter, reduce, forEach, setTimeout, addEventListener.",
"They make code reusable: you change the behavior by passing a different function."),
"Callbacks":N("A callback is a function you give to another function so it can call you back later, after some work is done. It is how JS handles things that take time, like timers and file reading.",
"Callback means: do this when you finish. JS does not stop and wait.",
"Order of output: normal code first, callback when the task completes.",
"Callback hell: callbacks inside callbacks inside callbacks, hard to read.",
"Promises and async/await are the cleaner modern replacement."),
"Event Loop":N("JavaScript has only one thread, so it can do one thing at a time. The event loop is the system that lets it handle slow tasks (timers, network) without freezing, by running them in the background and returning later.",
"1. Sync code runs on the Call Stack, line by line.",
"2. Timers and fetch are handed to Web APIs, which wait in the background.",
"3. Finished callbacks go to a queue. The event loop moves one to the stack only when the stack is empty.",
"Microtask queue (Promises) has higher priority than the callback queue (setTimeout), so Promise.then runs first."),
"Array Methods & Freeze":N("Array methods are built-in helpers to loop over and transform lists without writing manual for loops. Object.freeze protects an object from being changed.",
"map: returns a new array of the same length with each item changed.",
"filter: returns a new array with only the items that pass the test.",
"find: returns the first matching item (not an array). forEach: just loops, returns undefined.",
"freeze is shallow: nested objects inside can still change."),
"Data Types":N("Every value in JavaScript has a type. They are split in two groups: primitives (simple values) and objects (complex values). The group decides how the value is copied.",
"7 primitives: string, number, boolean, null, undefined, symbol, bigint.",
"Primitives are copied by value. Objects, arrays and functions are copied by reference (both variables point to the same thing).",
"typeof null is object. This is an old bug, not a real object.",
"== compares with type conversion, === compares value and type. Prefer ==="),

// ---------- REACT ----------
"React, Virtual DOM & Reconciliation":N("React is a JavaScript library for building user interfaces from small reusable pieces called components. Updating the real DOM is slow, so React keeps a light copy in memory (Virtual DOM) and updates the page smartly.",
"On change, React creates a new Virtual DOM and compares it with the old one. This comparison is called diffing.",
"Only the differences are applied to the real DOM. This whole process is reconciliation.",
"key must be unique and stable in lists so React knows which item changed. Avoid using array index when the list can reorder.",
"Why React: fast updates, reusable components, big community, works for web and mobile (React Native)."),
"React Fiber":N("Fiber is the rewritten core engine of React (since React 16). Old React rendered everything in one go and could freeze the screen. Fiber breaks the work into small units so it stays smooth.",
"Rendering work is split into small chunks called fibers.",
"React can pause, resume or drop low-priority work (like a big list) to handle urgent work (typing, clicks).",
"It enables features like concurrent rendering and Suspense."),
"State & Props":N("Both hold data for a component, but they have different jobs. State is data a component owns and can change. Props are data a component receives from its parent.",
"State changes cause a re-render. Use useState to create it.",
"Props are read-only. A child must never modify its own props.",
"Data flows one way: from parent to child (one-way data binding).",
"To change parent data from a child, the parent passes down a function as a prop."),
"Props Drilling vs Context":N("Props drilling means passing data through many components that do not need it, just to reach a deeply nested child. It works, but gets messy as the app grows.",
"Problem: middle components carry props they never use, so code is hard to maintain.",
"Fix 1: Context API for simple global data like theme or logged-in user.",
"Fix 2: Redux (or Zustand) for big, frequently changing global state.",
"Small app with 1 or 2 levels? Props are perfectly fine."),
"useState":N("useState is a hook that gives a function component its own memory. You get the current value and a setter function. Calling the setter updates the value and re-renders the component.",
"Syntax: const [value, setValue] = useState(initialValue).",
"Never change state directly (count++). Always use the setter.",
"State updates are asynchronous. If the new value depends on the old one, use setCount(c => c + 1).",
"For objects and arrays, create a new copy: setUser({...user, age: 20})."),
"useEffect & Lifecycle":N("useEffect lets you run side effects, meaning things outside rendering: fetching data, timers, event listeners, changing document title. It runs after the component is shown on screen.",
"No array: runs after every render. [] : runs once after first render (mount). [x]: runs when x changes.",
"The function you return is cleanup. It runs before the next effect and on unmount. Use it to clear timers and remove listeners.",
"Missing dependency in the array is a common bug (stale values).",
"Do not make the effect function itself async. Create an async function inside it."),
"useRef":N("useRef gives you a box with a .current property. Its value survives re-renders, but changing it does NOT cause a re-render. It is mostly used to reach DOM elements.",
"Attach to an element with ref={myRef}, then use myRef.current.focus().",
"Also stores values like timer IDs or previous values without re-rendering.",
"useState = changes UI. useRef = remembers silently."),
"useLayoutEffect":N("It works like useEffect, but runs earlier: after React updates the DOM but before the browser paints. So you can measure or change the layout without the user seeing a flicker.",
"Order: render, DOM updated, useLayoutEffect, browser paints, useEffect.",
"Use for measuring size or position (getBoundingClientRect) and tooltips.",
"It blocks painting, so use it only when needed. Default to useEffect."),
"useReducer":N("useReducer is an alternative to useState for complex state, especially when many updates depend on each other. Instead of setting state directly, you describe what happened (an action) and a reducer decides the new state.",
"Syntax: const [state, dispatch] = useReducer(reducer, initialState).",
"reducer(state, action) must be pure: return a new state, never change the old one.",
"Use when state has many fields or many update types (forms, carts, todos).",
"It is the same idea as Redux, but local to a component."),
"useContext":N("useContext reads a value from the nearest Provider above the component, so any child can get shared data without props being passed through each level.",
"Three steps: createContext, wrap with Provider and a value, read with useContext.",
"When the Provider value changes, every component using that context re-renders.",
"Good for theme, language, auth user. Not ideal for data that updates very often."),
"Performance: useMemo, useCallback, memo, lazy":N("React re-renders a component whenever its state or props change, and this also re-renders its children. These tools help skip unnecessary work, but use them only when you actually see slowness.",
"useMemo: remembers a calculated value until dependencies change.",
"useCallback: remembers a function so its reference stays the same.",
"React.memo: skips re-rendering a component if its props did not change. It only works well with stable props, which is why useMemo and useCallback are used together with it.",
"React.lazy + Suspense: load big components only when they are needed (code splitting)."),
"Pros, Cons & Interview Tips":N("Be ready to explain React in your own words, give one real example from your projects, and mention both strengths and limits.",
"Pros: fast updates, reusable components, huge ecosystem, flexible.",
"Cons: learning curve (hooks), needs extra libraries for routing and state, JSX looks odd at first.",
"Freshers: master useState, useEffect, props and Context.",
"Experienced: know useMemo, useCallback, Redux and performance tuning."),

// ---------- REDUX ----------
"Redux Core Terms":N("Redux is a library that keeps all shared app data (global state) in one place, so any component can read or update it in a predictable way. Use it when many components need the same data.",
"Store: the single object that holds all state.",
"Action: a plain object describing what happened, like {type: 'ADD', payload: 'task'}.",
"Reducer: a function (state, action) => newState that decides how state changes.",
"Data flow: component dispatches action, reducer updates store, components re-render."),
"Redux Toolkit Setup":N("Redux Toolkit (RTK) is the official, simpler way to write Redux. It removes most of the boilerplate. Setting it up takes five steps.",
"Install: npm install @reduxjs/toolkit react-redux.",
"Create store.js using configureStore and register your reducers.",
"Wrap the app in Provider so every component can reach the store.",
"The key you give in reducer: { counter: ... } becomes the name used in useSelector(state => state.counter)."),
"createSlice (Counter)":N("A slice is all the Redux logic of one feature (its state, reducers and actions) in a single file. createSlice builds the action creators for you.",
"name: slice name, used in action types.",
"initialState: starting data of that feature.",
"reducers: an object of functions. Each one gets (state, action).",
"Redux Toolkit uses Immer, so writing state.value += 1 is safe and is converted to an immutable update behind the scenes."),
"Using Redux in Components":N("Two hooks connect a component to the store: one to read data, one to send actions.",
"useSelector(state => ...): reads a value. Component re-renders when that value changes.",
"useDispatch(): returns dispatch. Call dispatch(actionCreator(payload)).",
"The argument you pass to the action creator becomes action.payload in the reducer."),
"Redux Thunk (API calls)":N("Reducers must be pure and cannot call APIs. Thunk is middleware that lets you write a function that does the async work and dispatches normal actions when done.",
"A thunk is a function that returns another function receiving dispatch (and getState).",
"Standard pattern: dispatch REQUEST (loading), then SUCCESS (data) or FAILURE (error).",
"State usually holds three things: loading, data, error.",
"Redux Toolkit also provides createAsyncThunk, which does this pattern for you."),
"Todo Slice: Common Mistakes":N("These are the typical bugs when writing reducers with Redux Toolkit. Knowing them shows real understanding.",
"push() on state is fine inside createSlice because of Immer.",
"filter() and map() return new arrays, so assign the result back to state, or nothing changes.",
"Do not both mutate state and return a new value in the same reducer.",
"Set the field you actually display (isDone), and use the same name everywhere."),

// ---------- NODE ----------
"What is Node.js":N("Node.js is a runtime that lets you run JavaScript outside the browser, on your computer or a server. It uses Chrome's V8 engine to run JS and was created by Ryan Dahl.",
"Not a language or framework. It is an environment to run JS.",
"Single-threaded with an event loop, and non-blocking I/O, so it handles many requests efficiently.",
"Great for APIs, real-time apps and streaming. Not ideal for heavy CPU work.",
"Comes with built-in modules like fs, http, os, path."),
"File System (fs)":N("The fs module lets Node read, write, update, rename and delete files and folders on your computer.",
"Sync methods (writeFileSync) block everything until done and return the result.",
"Async methods (writeFile) do not block and give you the result in a callback.",
"writeFile replaces the content, appendFile adds to the end.",
"unlink deletes a file. mkdir and rmdir create and remove folders."),
"Threads / CPU Cores":N("Your JavaScript code runs on a single thread, but your computer has many CPU cores. Knowing the core count helps you decide how many worker processes to run.",
"os.cpus().length returns the number of logical CPU cores.",
"One Node process uses mostly one core, so the rest sit idle.",
"Clusters use this number to start one worker per core."),
"Express & Versions":N("Express is a small framework on top of Node's http module. It makes creating servers, routes and middleware short and clean.",
"Routes: app.get, app.post, app.put, app.delete.",
"Middleware runs between request and response: express.json() reads JSON body, urlencoded() reads form data.",
"Version 4.18.2 means MAJOR.MINOR.PATCH. Major = breaking changes, minor = new features, patch = bug fixes.",
"req = incoming request, res = response you send back."),
"REST API vs SSR":N("Both send a response from the server, but the content is different. A REST API sends raw data (JSON) and the frontend decides how to show it. SSR sends a ready-made HTML page.",
"REST: res.json(). Client-server architecture. Frontend can be React, mobile app and more.",
"SSR: res.render() with a template engine like EJS. Good for SEO and fast first load.",
"Route parameter: /api/user/:id, read with req.params.id.",
"Methods: GET read, POST create, PUT/PATCH update, DELETE remove."),
"Headers":N("Headers are extra information sent along with every request and response. They describe the data, not the data itself, like the address label on a parcel.",
"Request headers: Authorization (token), Content-Type, Cookie, User-Agent.",
"Response headers: Content-Type, Set-Cookie, Cache-Control.",
"In Express use req.headers['name'] with lowercase names, and res.setHeader() to send one."),
"Authentication: Stateful vs Stateless":N("Authentication is proving who you are (login). After login, the server must recognize you on every next request. There are two ways to do that.",
"Stateful: server stores the session and gives a session ID, usually in a cookie. Easy to log out a user, but uses server memory.",
"Stateless: server stores nothing. It gives a signed token (JWT) that the client sends each time. Scales easily.",
"JWT has three parts: header, payload, signature. Never put passwords in it.",
"Authentication = who are you. Authorization = what are you allowed to do."),
"WebSockets (Socket.IO)":N("Normal HTTP is request then response, and the client must always ask first. WebSocket keeps one connection open so both client and server can send messages any time. Perfect for chat, live scores and notifications.",
"Bi-directional, full-duplex, over a single TCP connection.",
"Starts as an HTTP request and is upgraded using the Upgrade header.",
"Create the server with http.createServer(app) so Express and Socket.IO share one port.",
"socket.emit sends to one client, io.emit to everyone, socket.on listens for an event."),
"Streams":N("A stream sends data in small chunks instead of loading the whole file into memory first. This saves RAM and the user starts receiving data sooner.",
"readFile loads the full file in memory. createReadStream sends it piece by piece.",
"pipe() connects a readable stream to a writable one (for example, file to response).",
"Four types: Readable, Writable, Duplex, Transform.",
"Video streaming uses the Range header and status 206 (Partial Content)."),
"Clusters":N("A single Node process uses one CPU core. The cluster module starts several copies (workers) of your app so all cores share the incoming requests.",
"Primary process forks workers with cluster.fork(). Workers all listen on the same port.",
"Each worker has its own memory and process.pid.",
"If a worker crashes, the primary can listen for exit and fork a new one.",
"Result: higher throughput and better use of your hardware."),
"NGINX":N("NGINX (say engine-x) is a fast web server that usually sits in front of your Node apps and handles traffic before it reaches them.",
"Reverse proxy: forwards client requests to backend servers. Client does not know which server replied.",
"Load balancer: spreads requests across many servers.",
"Also does caching, serves static files, SSL/HTTPS and acts as API gateway.",
"Forward proxy is the opposite: it hides the clients from the server (like a VPN).")
};
